language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jameskeegan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jameskeegan/react-test npm test

after_success:
    - docker build -t jrakeegan/multi-client ./client
    - docker build -t jrakeegan/multi-nginx ./nginx
    - docker build -t jrakeegan/multi-server ./server
    - docker build -t jrakeegan/multi-worker ./worker
    # log in to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push them to docker hub
    - docker push jrakeegan/multi-client
    - docker push jrakeegan/multi-nginx 
    - docker push jrakeegan/multi-server
    - docker push jrakeegan/multi-worker